# Generated by Django 3.1.3 on 2020-12-15 09:06

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('album_type', models.CharField(choices=[('1', 'Single Extended Play Album'), ('2', 'Single Album'), ('3', 'Compilation Album'), ('4', 'Remix Album')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('1', 'Performer'), ('2', 'Director'), ('3', 'Producer'), ('4', 'Writer')], max_length=200)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online', models.BooleanField()),
                ('display_name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('duration', models.DurationField(validators=[django.core.validators.MinValueValidator(datetime.timedelta(0))])),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track', to='music.album')),
                ('artist_credits', models.ManyToManyField(related_name='artist_credit', through='music.Credit', to='music.Artist')),
            ],
            options={
                'unique_together': {('album', 'track_number')},
            },
        ),
        migrations.CreateModel(
            name='PlaylistContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.playlist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.track')),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(through='music.PlaylistContent', to='music.Track'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.user'),
        ),
        migrations.AddField(
            model_name='credit',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.track'),
        ),
        migrations.AddField(
            model_name='album',
            name='owner',
            field=models.ManyToManyField(related_name='album', to='music.Artist'),
        ),
        migrations.CreateModel(
            name='QueueTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_index', models.PositiveIntegerField()),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.user')),
            ],
            options={
                'unique_together': {('user', 'queue_index')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='playlist',
            unique_together={('user', 'name')},
        ),
        migrations.CreateModel(
            name='CurrentlyListening',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='music.user')),
                ('repeat_state', models.CharField(choices=[('0', 'No Repeat'), ('1', 'Repeat Current Song'), ('2', 'Repeat All Playlist')], max_length=200)),
                ('is_playing', models.BooleanField()),
                ('progress', models.DurationField()),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.queuetrack')),
            ],
        ),
    ]
