# Generated by Django 3.0.3 on 2020-12-16 16:04

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('1', 'Performer'), ('2', 'Director'), ('3', 'Producer'), ('4', 'Writer')], max_length=200)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('duration', models.DurationField(validators=[django.core.validators.MinValueValidator(datetime.timedelta(0))])),
                ('artist_credits', models.ManyToManyField(through='music.Credit', to='music.Artist')),
            ],
        ),
        migrations.AddField(
            model_name='credit',
            name='recording',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Recording'),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('album_type', models.CharField(choices=[('1', 'Single Extended Play Album'), ('2', 'Single Album'), ('3', 'Compilation Album'), ('4', 'Remix Album')], max_length=200)),
                ('owner', models.ManyToManyField(related_name='album', to='music.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_number', models.PositiveIntegerField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track', to='music.Album')),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Recording')),
            ],
            options={
                'unique_together': {('album', 'track_number')},
            },
        ),
    ]
