# Generated by Django 3.0.7 on 2020-12-18 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_type',
            field=models.CharField(choices=[('1', 'Single'), ('2', 'Extended Play'), ('3', 'Album')], max_length=200),
        ),
        migrations.AlterField(
            model_name='recording',
            name='artist_credits',
            field=models.ManyToManyField(related_name='artist_credit', through='music.Credit', to='music.Artist'),
        ),
        migrations.AlterField(
            model_name='track',
            name='recording',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track', to='music.Recording'),
        ),
        migrations.AlterUniqueTogether(
            name='credit',
            unique_together={('recording', 'artist', 'role')},
        ),
    ]
