# Generated by Django 3.0.7 on 2020-12-28 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20201218_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('-release_date',)},
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ('name',)},
        ),
    ]
