# Generated by Django 3.2.5 on 2021-09-30 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20201228_0216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'genre',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='genres',
            field=models.ManyToManyField(db_table='album_genre', related_name='albums', to='music.Genre'),
        ),
        migrations.AddField(
            model_name='recording',
            name='genres',
            field=models.ManyToManyField(db_table='recording_genre', related_name='recordings', to='music.Genre'),
        ),
    ]
