# Generated by Django 3.0.7 on 2020-12-18 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0002_auto_20201218_1357'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_index', models.PositiveIntegerField()),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Recording')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'queue_index')},
            },
        ),
        migrations.CreateModel(
            name='UserQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeat_state', models.CharField(choices=[('0', 'No Repeat'), ('1', 'Repeat Current Song'), ('2', 'Repeat All Playlist')], max_length=200)),
                ('is_playing', models.BooleanField()),
                ('progress', models.DurationField()),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listening.InQueue')),
            ],
        ),
    ]
