# Generated by Django 3.0.7 on 2020-12-19 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20201218_1357'),
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlistcontent',
            name='track',
        ),
        migrations.AddField(
            model_name='playlistcontent',
            name='recording',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='music.Recording'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(through='playlist.PlaylistContent', to='music.Recording'),
        ),
    ]
