# Generated by Django 3.0.7 on 2020-12-28 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_auto_20201219_1000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlistcontent',
            options={'ordering': ('time_added',)},
        ),
    ]
